version: "3"
services:
  shanebrewery:
    container_name: shanebrewery
    build:
      context: ./shanebrewery
      dockerfile: Dockerfile
    image: fionadawn/shanebrewery
    ports:
      - "8080:80"
    volumes:
      - ./shanebrewery:/usr/src/app
  breweryapi:
    container_name: breweryapi
    build:
      context: ./breweryapi
      dockerfile: Dockerfile
    image: fionadawn/breweryapi
    ports:
      - "3000:3000"
    volumes:
      - ./breweryapi:/usr/src/app
  thermometersensor:
    container_name: thermometersensor
    build:
      context: ./thermometersensor
      dockerfile: Dockerfile
    image: fionadawn/thermometersensor
    ports:
      - "5000:5000"
    volumes:
      - ./thermometersensor:/usr/src/app
