export const DELIVERY_LOADING = 'DELIVERY_LOADING';
export const DELIVERY_FAILURE = 'DELIVERY_FAILURE';
export const DELIVERY_START_SUCCESS = 'DELIVERY_START_SUCCESS';
export const DELIVERY_STOP_SUCCESS = 'DELIVERY_STOP_SUCCESS';
export const DELIVERY_PROGRESS = 'DELIVERY_PROGRESS';
export const CONTAINER_REMOVE_LOADING = 'CONTAINER_REMOVE_LOADING';
export const CONTAINER_REMOVE_SUCCESS = 'CONTAINER_REMOVE_SUCCESS';
export const CONTAINER_REMOVE_FAILURE = 'CONTAINER_REMOVE_FAILURE';
